# Generated by Django 5.2.1 on 2025-06-09 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhan_client_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
                ('master_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('new_quantity', models.IntegerField()),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('new_trigger_price', models.FloatField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitor Control',
                'verbose_name_plural': 'Monitor Controls',
            },
        ),
        migrations.CreateModel(
            name='OrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_order_id', models.CharField(max_length=100)),
                ('child_client_id', models.CharField(max_length=100)),
                ('child_order_id', models.CharField(max_length=100)),
                ('multiplier', models.FloatField()),
                ('original_quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('condition', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeframe', models.CharField(max_length=255)),
                ('initial_price', models.FloatField()),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.screener')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('stocks', models.JSONField()),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.screener')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsecode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('bsecode', models.CharField(blank=True, max_length=20, null=True)),
                ('per_chg', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('screener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lucky_Bulls.screener')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('token', models.TextField()),
                ('is_master', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('multiplier', models.FloatField(blank=True, help_text='Multiplier for child accounts', null=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('restrict_login', models.BooleanField(default=True, help_text='Restrict login based on IP')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Lucky_Bulls.tradingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradingaccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
