# Generated by Django 5.2.1 on 2025-06-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0002_remove_tradingaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
