# Generated by Django 5.2.1 on 2025-08-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0003_halalstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcontrol',
            name='monitor_type',
            field=models.CharField(choices=[('alerts', 'Alerts'), ('copy_trading', 'Copy Trading')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
