# Generated by Django 5.2.1 on 2025-08-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0004_monitorcontrol_monitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorcontrol',
            name='monitor_type',
            field=models.CharField(choices=[('alerts', 'Alerts'), ('copy_trading', 'Copy Trading')], max_length=50, unique=True),
        ),
    ]
