# Generated by Django 5.2.1 on 2025-08-07 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0005_alter_monitorcontrol_monitor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingaccount',
            options={'ordering': ['-is_master', 'name'], 'verbose_name': 'Trading Account', 'verbose_name_plural': 'Trading Accounts'},
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether the account is currently active'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last successful login time', null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses for API access'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='client_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='multiplier',
            field=models.FloatField(blank=True, help_text='Multiplier for child accounts (e.g., 1.5 for 1.5x trading)', null=True),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='Parent account for this child account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Lucky_Bulls.tradingaccount'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='restrict_login',
            field=models.BooleanField(default=True, help_text='Restrict login based on IP address'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_master', True)), fields=('is_master',), name='unique_master_account'),
        ),
    ]
