# Generated by Django 5.2.1 on 2025-08-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucky_Bulls', '0006_alter_tradingaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingaccount',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='tradingaccount',
            name='unique_master_account',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='amo_time',
            field=models.CharField(blank=True, choices=[('OPEN', 'Market Open'), ('OPEN_30', '30 Minutes After Open'), ('OPEN_60', '60 Minutes After Open')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Lucky_Bulls.tradingaccount'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='restrict_login',
            field=models.BooleanField(default=True, help_text='Restrict login based on IP'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='token',
            field=models.TextField(),
        ),
    ]
